name GITHUB_ACTIONS flow

on:
  push:
    branches:
      - main


jobs:
  check-changes: 
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.check_client.outputs.client_changed }}
      server_changed: ${{ steps.check_server.outputs.server_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Check for changes in client directory
        id: check_client
        uses: dorny/paths-filter@v3
        with:
          filters:"client/**"

      - name: Check for changes in server directory
        id: check_server
        uses: dorny/paths-filter@v3
        with:
          filters:"server/**"
  client:
      needs: check-changes
      runs-on: ubuntu-latest
      if: needs.check-changes.outputs.client_changed == 'true'
      steps:
        - name: Nyc working 
          run: echo "Client directory has changes. Proceeding with client job."
  server:
      needs: check-changes
      runs-on: ubuntu-latest
      if: needs.check-changes.outputs.server_changed == 'true'
      steps:
        - name: Nyc working 
          run: echo "Server directory has changes. Proceeding with server job."